openapi: 3.0.0
info:
  title: youStream Comments
  version: 1.0.0
paths:
  /api/v1/comments/create-comment/{videoIdOrCommunnityPostId}:
    post:
      summary: Create a comment for a video or community post
      tags:
        - Comments
      parameters:
        - in: path
          name: videoIdOrCommunnityPostId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "201":
          description: Comment created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
              examples:
                sample:
                  value:
                    _id: "64c..."
                    content: "Nice video!"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/comments/delete-comment/{commentId}:
    delete:
      summary: Delete a comment by ID
      tags:
        - Comments
      parameters:
        - in: path
          name: commentId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Comment deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/comments/all-comments/{videoIdOrCommunnityPostId}:
    get:
      summary: Get all comments for a video or community post
      tags:
        - Comments
      parameters:
        - in: path
          name: videoIdOrCommunnityPostId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comment"
              examples:
                sample:
                  value:
                    - _id: "64c..."
                      content: "Nice video!"
                    - _id: "64c..."
                      content: "Great post"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/comments/update-comment/{commentId}:
    put:
      summary: Update a comment by ID
      tags:
        - Comments
      parameters:
        - in: path
          name: commentId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        "200":
          description: Comment updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/comments/comment/{commentId}:
    get:
      summary: Get a comment by ID
      tags:
        - Comments
      parameters:
        - in: path
          name: commentId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Comment details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
              examples:
                sample:
                  value:
                    _id: "64c..."
                    content: "Nice video!"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
