openapi: 3.0.0
info:
  title: youStream Videos
  version: 1.0.0
paths:
  /api/v1/videos/all-videos:
    get:
      summary: Get all videos
      tags:
        - Videos
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Video"
              examples:
                sample:
                  value:
                    - _id: "64b..."
                      title: "My first video"
                      description: "A demo video"
                    - _id: "64b..."
                      title: "Another video"
                      description: "Second demo"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/videos/{videoId}:
    get:
      summary: Get a video by ID
      tags:
        - Videos
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Video details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Video"
              examples:
                sample:
                  value:
                    _id: "64b..."
                    title: "My first video"
                    description: "A demo video"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/videos/upload-video:
    post:
      summary: Upload a new video
      tags:
        - Videos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                video:
                  type: string
                  format: binary
                thumbnail:
                  type: string
                  format: binary
      responses:
        "201":
          description: Video uploaded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Video"
        "400":
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/videos/update-video/{videoId}:
    put:
      summary: Update a video by ID
      tags:
        - Videos
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                video:
                  type: string
                  format: binary
                thumbnail:
                  type: string
                  format: binary
      responses:
        "200":
          description: Video updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Video"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/videos/delete-video/{videoId}:
    delete:
      summary: Delete a video by ID
      tags:
        - Videos
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Video deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/v1/videos/toggle-publish/{videoId}:
    patch:
      summary: Toggle publish status of a video
      tags:
        - Videos
      parameters:
        - in: path
          name: videoId
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Publish status toggled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Video"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
